### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by bbigras** [aviraldg/matrix-appservice-slack-api#1]
I'm trying to test [alertmanager](https://prometheus.io/docs/alerting/configuration/#slack-receiver-<slack_config) with matrix-appservice-slack-api.

Maybe it's because it uses [attachments](https://api.slack.com/docs/message-attachments).

```
{ channel: 'bidon',
  username: 'AlertManager',
  attachments: [ { text: 'patate', fallback: '', mrkdwn_in: [Object] } ] }
TypeError: Cannot read property 'replace' of undefined
    at webhookHandler (/home/bbigras/tmp/matrix-appservice-slack-api/lib/app.js:70:28)
    at Layer.handle [as handle_request] (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/layer.js:95:5)
    at /home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/index.js:277:22
    at param (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/index.js:349:14)
    at param (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/index.js:410:3)
    at next (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/index.js:271:10)
    at urlencodedParser (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/body-parser/lib/types/urlencoded.js:82:7)
    at Layer.handle [as handle_request] (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/index.js:312:13)
    at /home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/index.js:330:12)
    at next (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/index.js:271:10)
```

**Comment by bbigras** [comment]
Sorry for the delay. This is the JSON that alertmanager is sending with the minimal config (see "Slack receiver" on https://prometheus.io/docs/alerting/configuration/)

Note that alertmanager expects me to provide a channel even if I provide one in the URL.
config

``` yml
  slack_configs:
  - api_url: "http://10.1.10.94:8000/hooks/!rfqUsprbuDhLjgSDaY:localhost"
    channel: "test"
```

JSON

``` json
{
  "channel": "test",
  "username": "AlertManager",
  "attachments": [
    {
      "title": "[FIRING:1] InstanceDown (up localhost:17180 go-importeplanif codelab-monitor)",
      "title_link": "http://ubuntunew:9093/#/alerts?receiver=bruno",
      "text": "",
      "fallback": "[FIRING:1] InstanceDown (up localhost:17180 go-importeplanif codelab-monitor) | http://ubuntunew:9093/#/alerts?receiver=bruno",
      "color": "danger",
      "mrkdwn_in": [
        "fallback",
        "pretext",
        "text"
      ]
    }
  ]
}
```

log

```
{ channel: 'test',
  username: 'AlertManager',
  attachments: 
   [ { title: '[FIRING:1] InstanceDown (up localhost:17180 go-importeplanif codelab-monitor)',
       title_link: 'http://ubuntunew:9093/#/alerts?receiver=bruno',
       text: '',
       fallback: '[FIRING:1] InstanceDown (up localhost:17180 go-importeplanif codelab-monitor) | http://ubuntunew:9093/#/alerts?receiver=bruno',
       color: 'danger',
       mrkdwn_in: [Object] } ] }
TypeError: Cannot read property 'replace' of undefined
    at webhookHandler (/home/bbigras/tmp/matrix-appservice-slack-api/lib/app.js:70:28)
    at Layer.handle [as handle_request] (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/layer.js:95:5)
    at /home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/index.js:277:22
    at param (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/index.js:349:14)
    at param (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/index.js:410:3)
    at next (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/index.js:271:10)
    at urlencodedParser (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/body-parser/lib/types/urlencoded.js:82:7)
    at Layer.handle [as handle_request] (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/index.js:312:13)
    at /home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/index.js:330:12)
    at next (/home/bbigras/tmp/matrix-appservice-slack-api/node_modules/express/lib/router/index.js:271:10)
```

**Comment by bbigras** [comment]
Any progress?

**Comment by aviraldg** [comment]
Apologies, @brunoqc, have been a little caught up with releasing RTE on Vector. I'll get on this this weekend.

**Comment by bbigras** [comment]
No need for apologies. It was just a reminder in case you forgot. No hurry. :)

I saw the RTE entry in /develop changelog. Nice work.
